### ISSUE TITLE
Problem with Gparted and Synaptic

### ISSUE THREAD

**Issue by mnwstl** [darkomarko42/Marwaita-ubuntu#1]
Hi!
I'm using the Marwaita Ubuntu Dark theme and noticed that Gparted and Synaptic have adapted to the theme only in the title bar, with the window remaining clear. I don't know if there's anything missing or if I did something wrong.

**Comment by darkomarko42** [comment]
can you post a screenshot? maybe you have install the flatpak version

**Comment by darkomarko42** [comment]
https://imgur.com/a/DnBuPFG

**Comment by mnwstl** [comment]
I downloaded the zip file from https://www.gnome-look.org/p/1352833, unzipped and copied it to /home/mmn/.themes/. I used GNOME Tweaks to select.

Screenshot: https://i.imgur.com/9AB0sIO.jpg

**Comment by mnwstl** [comment]
I had the idea to copy the files to the /usr/share/themes/ folder. I don't quite understand what's going on, but the fact is, it's as expected.

Screenshot: https://i.imgur.com/YS0HH1c.jpg

Taking the opportunity, I ask if I could not reduce the height of the title bar of the windows. I use the theme on a laptop and that way would optimize the screen space.
